# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
np.show_config()

2.3.1
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.43.34808",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.2",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.43.34808",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.29",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-9tmma_o0/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib d

c:\Users\jomin\Documents\Code\CodingClub\AI-Mafia-Machine-Learning\mafia\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10

In [7]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [8]:
np.array([1,2,3]).nbytes

24

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [9]:
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\jomin\documents\code\codingclub\ai-mafia-machine-learning\mafia\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locatio

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [11]:
arr = np.empty(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 1., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [13]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [14]:
arr = np.arange(5)
arr[::-1]

array([4, 3, 2, 1, 0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
arr = np.arange(0,9)
arr = arr.reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [18]:
arr = np.array([1,2,0,0,4,0])
np.where(arr != 0)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix

In [20]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [21]:
np.random.random((3,3,3))

array([[[0.38824307, 0.78029703, 0.35486593],
        [0.07448246, 0.18200291, 0.17210857],
        [0.68996954, 0.47338791, 0.95184409]],

       [[0.1647793 , 0.10911568, 0.41974938],
        [0.60132943, 0.90295658, 0.57506789],
        [0.17473525, 0.09172853, 0.90593289]],

       [[0.99288698, 0.87912952, 0.23272358],
        [0.74406763, 0.67774697, 0.83916065],
        [0.60666012, 0.97781237, 0.21797701]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [24]:
arr = np.random.random((10,10))
print(arr)
print(np.min(arr))
print(np.max(arr))

[[0.93738731 0.49050843 0.01778708 0.63419594 0.33186712 0.56193636
  0.20206007 0.43605432 0.25549892 0.20036396]
 [0.92711773 0.71847866 0.39243171 0.39542391 0.61473914 0.95653805
  0.10989533 0.56223502 0.28789752 0.84822001]
 [0.71617561 0.33162787 0.46794238 0.49900746 0.44340376 0.05581789
  0.61133015 0.76113299 0.70268434 0.49644377]
 [0.55272344 0.77050253 0.50912654 0.51115833 0.23816474 0.97390349
  0.09610549 0.70986703 0.49427831 0.40849478]
 [0.7582081  0.5521428  0.87775043 0.02410814 0.98968999 0.68776648
  0.47041458 0.86999869 0.97121583 0.30340972]
 [0.78990917 0.28154026 0.72508532 0.33566361 0.37774983 0.46144681
  0.4872724  0.36432286 0.25028104 0.10395477]
 [0.62683551 0.41744299 0.1131819  0.14136474 0.98595334 0.47588366
  0.01875764 0.2423087  0.96358339 0.33254456]
 [0.58185403 0.48566575 0.43679344 0.70952794 0.96452678 0.30679768
  0.47187271 0.14009424 0.37809982 0.85713807]
 [0.48053046 0.14748641 0.60330102 0.33639363 0.77801638 0.92935111
  0.51692032

#### 14. Create a random vector of size 30 and find the mean value

In [26]:
arr = np.random.random(30)
print(arr)
np.mean(arr)

[0.80399336 0.26229768 0.66844754 0.3056721  0.06825593 0.31973484
 0.37826826 0.61789006 0.04278678 0.90624242 0.14051795 0.69350682
 0.62774248 0.68550561 0.60257675 0.33604128 0.88252703 0.9744679
 0.14870098 0.17169433 0.8029129  0.35708307 0.61565768 0.27870454
 0.17283004 0.9302052  0.36717726 0.95127947 0.46017312 0.98572374]


np.float64(0.5186205708290357)

#### 15. Create a 2d array with 1 on the border and 0 inside

In [28]:
arr = np.zeros((4,4))
arr[0,:] = 1
arr[:,0] = 1
arr[:,3] = 1
arr[3,:] = 1
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [32]:
arr = np.random.randint(0,10,16)
arr = arr.reshape((4,4))
arr[0,:] = 0
arr[:,0] = 0
arr[:,3] = 0
arr[3,:] = 0
arr

array([[0, 0, 0, 0],
       [0, 4, 6, 0],
       [0, 4, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [34]:
print(
    0 * np.nan,
    np.nan == np.nan,
    np.inf > np.nan,
    np.nan - np.nan,
    np.nan in set([np.nan]),
    0.3 == 3 * 0.1,
    sep='\n'
)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [41]:
arr = np.full((5,5), 5)
for i in range(4):
    arr[i+1,i]=i+1
arr

array([[5, 5, 5, 5, 5],
       [1, 5, 5, 5, 5],
       [5, 2, 5, 5, 5],
       [5, 5, 3, 5, 5],
       [5, 5, 5, 4, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [48]:
arr = np.full((8,8),'⬛')
arr[::2,1::2] = '⬜'
arr[1::2,::2] = '⬜'
arr

array([['⬛', '⬜', '⬛', '⬜', '⬛', '⬜', '⬛', '⬜'],
       ['⬜', '⬛', '⬜', '⬛', '⬜', '⬛', '⬜', '⬛'],
       ['⬛', '⬜', '⬛', '⬜', '⬛', '⬜', '⬛', '⬜'],
       ['⬜', '⬛', '⬜', '⬛', '⬜', '⬛', '⬜', '⬛'],
       ['⬛', '⬜', '⬛', '⬜', '⬛', '⬜', '⬛', '⬜'],
       ['⬜', '⬛', '⬜', '⬛', '⬜', '⬛', '⬜', '⬛'],
       ['⬛', '⬜', '⬛', '⬜', '⬛', '⬜', '⬛', '⬜'],
       ['⬜', '⬛', '⬜', '⬛', '⬜', '⬛', '⬜', '⬛']], dtype='<U1')

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [49]:
np.unravel_index(99, (6,7,8))

(np.int64(1), np.int64(5), np.int64(3))